### PR TITLE
Fix/49 date parsing

### LINKED ISSUE #49: various RFC5322 date parsing and type issues
We have to parse dates better.  Issues include:

- Day of week is optional, but we require it
- Seconds are option, but we require them
- Various valid whitespace occurrence is rejected by us
- We erase the timezone offset and return a `UTCTime`.  We should keep the offset in the data we return (i.e. we have to change the type).

See https://tools.ietf.org/html/rfc5322#section-3.3

### PR DESCRIPTION
**Pull request by frasertweedale**
Fixes #49.

@veprbl do the changes in this PR address your issues?  I have included your commits (with some changes) in this PR, but decided to build a proper parser and fix all the issues in #49 for good (hopefully).

### CODE REVIEW

**Comment by frasertweedale** [comment]
@romanofski I'll see in the next couple of days what the impact on purebred will be.  It should not be too large, I think.

**Review by veprbl — APPROVED** [review]
Works for me. Thank you!

**Review by romanofski — APPROVED** [review]

**Comment by frasertweedale** [comment]
This is not yet good-to-go.  Checking against a large corpus of mail I found mails using the ["RFC 5322 section 4.3 - obsolete date and time"](https://tools.ietf.org/html/rfc5322#section-4.3) construction.  Specifically, obsolete timezone definitions.

**Comment by frasertweedale** [comment]
Closing; replaced by https://github.com/purebred-mua/purebred-email/pull/65 .

**Pull request closed without merging**
